services:
  - type: web
    name: skillswap-app
    env: node
    plan: free
    buildCommand: npm run railway-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
